name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Super Linter
        run: |
          git clone https://github.com/super-linter/super-linter.git super-linter
          cd super-linter
          chmod +x ./bin/install.sh

      - name: Cache Super Linter configuration
        uses: actions/cache@v3
        with:
          path: superlinter.yaml
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/superlinter.yaml') }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: Cache Java 21 setup
        uses: actions/cache@v4.0.0
        with:
          path: ~/.java
          key: ${{ runner.os }}-java-21-${{ hashFiles('**/*.release') }}
          restore-keys: |
            ${{ runner.os }}-java-21-

      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: Build project
        run: mvn clean install

      - name: Test project
        run: mvn test

      - name: Lint project
        run: mvn superlinter:check
