name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Java 21 setup
        uses: actions/cache@v4.0.0
        with:
          path: ~/.java
          key: ${{ runner.os }}-java-21-${{ hashFiles('**/*.release') }}
          restore-keys: |
            ${{ runner.os }}-java-21-

      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: Lint Code Base CICD
        uses: github/super-linter@v4

      - name: Build project
        run: mvn clean install

      - name: Test project
        run: mvn test

      - name: Lint project
        run: mvn superlinter:check
